title: "לוח דרושים - Jobs"
description: "לוח מודעות דרושים לעובדים חיפושי משרות ופרסום משרות"
url: "https://anlominus.github.io"
baseurl: "/Jobs"
lang: he
timezone: Asia/Jerusalem
author: "AnLoMinus"
email: "contact@example.com"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:title/

header_pages:
  - categories.md
  - about.md
  - tags.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AnLoMinus"
      lang: he
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      lang: he

collections:
  posts:
    output: true

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CHANGELOG.md
  - LICENSE
  - node_modules

feed:
  path: feed.xml

